spring:
  application:
    name: yingxin-service
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
    url: jdbc:h2:file:~/.h2/servicedb
    driverClassName: org.h2.Driver
    spring.datasource.username: sa
    spring.datasource.password:

server:
  port: 8089
  tomcat:
    uri-encoding: utf-8

